### ISSUE TITLE
chain name keep

### ISSUE THREAD

**Issue by AndyDanian** [bioexcel/biobb_amber#2]
Hello Everyone!

I'm using leap_gen_top class 

https://biobb-amber.readthedocs.io/en/latest/_modules/leap/leap_gen_top.html#LeapGenTop

I need to keep chain name into pdb output file, 

what solution suggest me?

Thanks
[rlw_after_leap.txt](https://github.com/bioexcel/biobb_amber/files/8743363/rlw_after_leap.txt)
[rlw_before_leap.txt](https://github.com/bioexcel/biobb_amber/files/8743364/rlw_before_leap.txt)

**Comment by adamhospital** [comment]
Hi Andy,

I'm afraid there's no straightforward answer to this question :S 

First of all, we need to note that the output pdb is the one generated by the tool wrapped (tleap). In this case, this pdb doesn't contain chain ids, as it matches the generated parmtop and crd files (which don't have any chain id info either). 

There were attempts to maintain this information using additional scripts in Amber (see http://archive.ambermd.org/201210/0322.html), but not sure if it works using the reference pdb (the one with chain information) with a different number of atoms from the generated parmtop (e.g. added hydrogen atoms). 

I don't have a solution to suggest you, other than parse the chain id information from the reference pdb and integrate it to the new pdb :( This is something we could think as an improvement for the building block, but we will need to remind that the parmtop file will not have this info. There are also ways to add this info in the parmtop files, but is not standard and most of the parmtop parsers will not read it properly.  

Thanks for using our tools!
