### ISSUE TITLE
Incomplete legend structure after lean_gen_top

### ISSUE THREAD

**Issue by ademariag** [bioexcel/biobb_amber#3]
We're having an issue with the following piece of code when using leap_gen_top (from biobb_amber==3.6.2)

```
prop = {"forcefield": ["protein.ff14SB", "gaff"]}

leap_gen_top(
    input_pdb_path=output_post_merge.path,
    input_lib_path=output_acpype_lib.path,
    input_frcmod_path=output_acpype_frcmod.path,
    output_pdb_path=output_pdb_path,
    output_top_path=output_top_path,
    output_crd_path=output_crd_path,
    properties=prop,
)


```

The input is taken from 2ZFF.pdb, modified to only include a single chain (H), however the output_pdb_path produces an incomplete ligand structure with several bonds missing eg the bond that closes the 5-membered ring of proline amongst others. 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/32644550/187931886-dac1ac19-1297-4544-8210-e80d69cd2f76.png">

[bundled.hrqyscwi.pdb.txt](https://github.com/bioexcel/biobb_amber/files/9470475/bundled.hrqyscwi.pdb.txt)
[complex-prep-lig_1a-.structure.leap.8toeg6l6.pdb.txt](https://github.com/bioexcel/biobb_amber/files/9470491/complex-prep-lig_1a-.structure.leap.8toeg6l6.pdb.txt)

 This seems to be due to corruption of the CONECT data?

**Comment by adamhospital** [comment]
Hi, 

I haven't been able to reproduce the problem, but I leave you attached the BioBB Amber complex setup modified to take the chain H of the 2ZFF pdb and run the setup of the system. I only recommend to manually modify the name of the ligand from 53U to UNL before running the workflow, as sometimes programs have problems or strange behaviours with ligand names starting with a number (for example ACPype here is replacing 53U by R53U and this breaks the workflow automation). 

Notes: the workflow should run using the same environment prepared for the [BioBB Amber Protein MD setup workflows](https://github.com/bioexcel/biobb_wf_amber_md_setup). The markdown has not been modified for the sake of time, and some information might not correspond to the content of the cells. 

Hope this helps!

[BioBB_2ZFF_53U.zip](https://github.com/bioexcel/biobb_amber/files/9471569/BioBB_2ZFF_53U.zip)
