### ISSUE TITLE
Leap_solvate can't create a cubic box.

### ISSUE THREAD

**Issue by ndonyapour** [bioexcel/biobb_amber#4]
Hello,

I'm creating a water box using the following code, but it doesn't make a cubic box. I looked at the `leap_solvate` code, and it seems that the order of Amber's `solvatebox` command is not as explained [here](https://ambermd.org/tutorials/advanced/tutorial2/section1.htm).

``` python
from biobb_amber.leap.leap_solvate import leap_solvate
output_solv_pdb_path = 'structure.solv.pdb'
output_solv_top_path = 'structure.solv.parmtop'
output_solv_crd_path = 'structure.solv.rst7'

prop = {
    "forcefield" : ["protein.ff14SB","gaff"],
    "water_type": "TIP3PBOX",
    "distance_to_molecule": 9.0,
    "box_type": "cubic",
    "iso": True,
    "closenes": 1.0,
    "remove_tmp": False
}

# Create and launch biobb_amber leap_solvate
leap_solvate(input_pdb_path='complex_min_vac.pdb',
             input_lib_path='ligand_params.lib',
             input_frcmod_path='ligand_params.frcmod',
             output_pdb_path=output_solv_pdb_path,
             output_top_path=output_solv_top_path,
             output_crd_path=output_solv_crd_path,
             properties=prop)
```

The order of arguments for `solavtebox`  is `solvatebox solute solvent buffer [ "iso" ] [ closeness ]` while `iso` comes after  `closeness` [in this code](https://github.com/bioexcel/biobb_amber/blob/4cc9697846831f2832293fb7421b453f16211b18/biobb_amber/leap/leap_solvate.py#L264).

``` python
  # Generating box + adding water molecules
  leapin.write(box_command + " mol " + self.water_type + " " + str(self.distance_to_molecule) + " " + str(self.closeness))
  leapin.write(" iso \n") if self.iso else leapin.write("\n")
                
```                
Switching `iso` and  `closeness` fixes the bug. I have attached my input files. If this is the case I'll submit a PR.

Thank you!
[inputs.zip](https://github.com/bioexcel/biobb_amber/files/10501727/inputs.zip)

**Comment by gbayarri** [comment]
Hi, @ndonyapour 

Can you please submit your PR?

Thanks!

**Comment by ndonyapour** [comment]
Done https://github.com/bioexcel/biobb_amber/pull/5!

Thanks,
Nazanin
